# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'
  dockerId: mansoor4win

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io --password-stdin
    docker push $(dockerId).azurecr.io/$(imageName)

- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker push $(dockerId)/$(imageName)

  env:
    pswd: Smb@12345
